DOC_CATEGORIES = {
    "guides": {
        "title": "Documentation Guides",
        "url": "https://discordpy.readthedocs.io/en/stable/",
        "topics": {
            "quickstart": ("Quickstart", "Basic bot setup and first run.", "https://discordpy.readthedocs.io/en/stable/quickstart.html"),
            "logging": ("Setting Up Logging", "Configure Python logging for discord.py diagnostics.", "https://discordpy.readthedocs.io/en/stable/logging.html"),
            "intents guide": ("Intents Guide", "How gateway intents and privileged intents work.", "https://discordpy.readthedocs.io/en/stable/intents.html"),
            "commands guide": ("Commands Guide", "User guide for the commands extension.", "https://discordpy.readthedocs.io/en/stable/ext/commands/commands.html"),
            "cogs guide": ("Cogs Guide", "Organizing commands and listeners with cogs.", "https://discordpy.readthedocs.io/en/stable/ext/commands/cogs.html"),
            "extensions guide": ("Extensions Guide", "Loading and reloading Python extension modules.", "https://discordpy.readthedocs.io/en/stable/ext/commands/extensions.html"),
            "tasks guide": ("Tasks Guide", "Creating managed background loops.", "https://discordpy.readthedocs.io/en/stable/ext/tasks/"),
            "faq": ("FAQ", "Frequently asked discord.py questions.", "https://discordpy.readthedocs.io/en/stable/faq.html"),
            "migrating": ("Migrating", "Migration notes for discord.py versions.", "https://discordpy.readthedocs.io/en/stable/migrating.html"),
            "version guarantees": ("Version Guarantees", "Compatibility and versioning guarantees.", "https://discordpy.readthedocs.io/en/stable/version_guarantees.html"),
        },
    },
    "events": {
        "title": "Event Reference",
        "url": "https://discordpy.readthedocs.io/en/stable/api.html#event-reference",
        "topics": {
            "on_ready": ("on_ready", "Called when the client is ready after login.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.on_ready"),
            "on_connect": ("on_connect", "Called when the client connects to Discord.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.on_connect"),
            "on_disconnect": ("on_disconnect", "Called when the client disconnects from Discord.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.on_disconnect"),
            "on_message": ("on_message", "Called when a message is created and received.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.on_message"),
            "on_message_delete": ("on_message_delete", "Called when a cached message is deleted.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.on_message_delete"),
            "on_message_edit": ("on_message_edit", "Called when a cached message is edited.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.on_message_edit"),
            "on_reaction_add": ("on_reaction_add", "Called when a reaction is added to a cached message.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.on_reaction_add"),
            "on_raw_reaction_add": ("on_raw_reaction_add", "Called when a reaction is added regardless of message cache.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.on_raw_reaction_add"),
            "on_member_join": ("on_member_join", "Called when a member joins a guild.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.on_member_join"),
            "on_member_remove": ("on_member_remove", "Called when a member leaves or is kicked.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.on_member_remove"),
            "on_guild_join": ("on_guild_join", "Called when the client joins a guild.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.on_guild_join"),
            "on_guild_remove": ("on_guild_remove", "Called when the client leaves or is removed from a guild.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.on_guild_remove"),
            "on_interaction": ("on_interaction", "Called when an interaction is received.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.on_interaction"),
            "on_voice_state_update": ("on_voice_state_update", "Called when a member changes voice state.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.on_voice_state_update"),
            "on_poll_vote_add": ("on_poll_vote_add", "Called when a cached poll gains a vote.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.on_poll_vote_add"),
            "on_poll_vote_remove": ("on_poll_vote_remove", "Called when a cached poll loses a vote.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.on_poll_vote_remove"),
            "on_raw_poll_vote_add": ("on_raw_poll_vote_add", "Called when a poll gains a vote regardless of message cache.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.on_raw_poll_vote_add"),
            "on_raw_poll_vote_remove": ("on_raw_poll_vote_remove", "Called when a poll loses a vote regardless of message cache.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.on_raw_poll_vote_remove"),
            "on_error": ("on_error", "Fallback event error handler.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.on_error"),
        },
    },
    "core": {
        "title": "Core Client API",
        "url": "https://discordpy.readthedocs.io/en/stable/api.html",
        "topics": {
            "client": ("discord.Client", "Base Discord gateway and HTTP client.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Client"),
            "shardinfo": ("discord.ShardInfo", "Information about one gateway shard.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.ShardInfo"),
            "intents": ("discord.Intents", "Gateway event subscription flags.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Intents"),
            "membercacheflags": ("discord.MemberCacheFlags", "Controls member cache policy.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.MemberCacheFlags"),
            "allowedmentions": ("discord.AllowedMentions", "Controls mention parsing in messages.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.AllowedMentions"),
            "permissions": ("discord.Permissions", "Discord permission bitfield.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Permissions"),
            "permissionoverwrite": ("discord.PermissionOverwrite", "Channel-specific permission overwrites.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.PermissionOverwrite"),
            "colour": ("discord.Colour", "Discord color helper class.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Colour"),
            "object": ("discord.Object", "Lightweight object with an ID.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Object"),
            "utils": ("discord.utils", "Utility functions such as find, get, format_dt, utcnow.", "https://discordpy.readthedocs.io/en/stable/api.html#utility-functions"),
        },
    },
    "models": {
        "title": "Discord Models",
        "url": "https://discordpy.readthedocs.io/en/stable/api.html",
        "topics": {
            "guild": ("discord.Guild", "A Discord server.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Guild"),
            "member": ("discord.Member", "A user inside a guild.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Member"),
            "user": ("discord.User", "A Discord user account.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.User"),
            "clientuser": ("discord.ClientUser", "The connected bot user.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.ClientUser"),
            "role": ("discord.Role", "A guild role.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Role"),
            "message": ("discord.Message", "A Discord message.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Message"),
            "attachment": ("discord.Attachment", "A file attached to a message.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Attachment"),
            "embed": ("discord.Embed", "Rich message embed payload.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Embed"),
            "reaction": ("discord.Reaction", "A reaction on a message.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Reaction"),
            "emoji": ("discord.Emoji", "Custom guild emoji.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Emoji"),
            "partialemoji": ("discord.PartialEmoji", "Partial emoji payload.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.PartialEmoji"),
            "sticker": ("discord.Sticker", "Guild or standard sticker.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Sticker"),
            "soundboard": ("discord.SoundboardSound", "Guild soundboard sound.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.SoundboardSound"),
            "poll": ("discord.Poll", "Native Discord poll message object.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Poll"),
            "pollanswer": ("discord.PollAnswer", "One answer inside a native Discord poll.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.PollAnswer"),
            "pollresults": ("discord.PollResults", "Vote result data for a native Discord poll.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.PollResults"),
            "invite": ("discord.Invite", "Discord invite model.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Invite"),
            "template": ("discord.Template", "Guild template model.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Template"),
            "auditlogentry": ("discord.AuditLogEntry", "One guild audit log entry.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.AuditLogEntry"),
            "scheduled event": ("discord.ScheduledEvent", "Guild scheduled event.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.ScheduledEvent"),
        },
    },
    "channels": {
        "title": "Channels and Threads",
        "url": "https://discordpy.readthedocs.io/en/stable/api.html#discord-api-models",
        "topics": {
            "textchannel": ("discord.TextChannel", "Guild text channel.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.TextChannel"),
            "voicechannel": ("discord.VoiceChannel", "Guild voice channel.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.VoiceChannel"),
            "stagechannel": ("discord.StageChannel", "Guild stage channel.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.StageChannel"),
            "categorychannel": ("discord.CategoryChannel", "Guild category channel.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.CategoryChannel"),
            "forumchannel": ("discord.ForumChannel", "Forum channel.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.ForumChannel"),
            "mediachannel": ("discord.MediaChannel", "Media channel.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.MediaChannel"),
            "thread": ("discord.Thread", "Thread channel.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Thread"),
            "dmchannel": ("discord.DMChannel", "Direct message channel.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.DMChannel"),
            "groupchannel": ("discord.GroupChannel", "Group direct message channel.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.GroupChannel"),
            "webhook": ("discord.Webhook", "Webhook object.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Webhook"),
            "partialwebhookguild": ("discord.PartialWebhookGuild", "Partial guild from webhook data.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.PartialWebhookGuild"),
            "partialwebhookchannel": ("discord.PartialWebhookChannel", "Partial channel from webhook data.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.PartialWebhookChannel"),
        },
    },
    "commands": {
        "title": "commands Extension",
        "url": "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html",
        "topics": {
            "bot": ("commands.Bot", "Command-aware bot client.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Bot"),
            "autoshardedbot": ("commands.AutoShardedBot", "Command bot with automatic sharding.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.AutoShardedBot"),
            "context": ("commands.Context", "Invocation context for prefix and hybrid commands.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Context"),
            "command": ("commands.Command", "Prefix command object.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Command"),
            "group": ("commands.Group", "Command with subcommands.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Group"),
            "hybridcommand": ("commands.HybridCommand", "Command usable as prefix and slash.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.HybridCommand"),
            "hybridgroup": ("commands.HybridGroup", "Group usable as prefix and slash.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.HybridGroup"),
            "cog": ("commands.Cog", "Class container for commands and listeners.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Cog"),
            "groupcog": ("commands.GroupCog", "Cog represented as an application command group.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.GroupCog"),
            "converter": ("commands.Converter", "Custom prefix command converter base.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Converter"),
            "flagconverter": ("commands.FlagConverter", "Flag-style command argument converter.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.FlagConverter"),
            "cooldown": ("commands.cooldown", "Apply rate limits to commands.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.cooldown"),
            "maxconcurrency": ("commands.max_concurrency", "Limit concurrent command usage.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.max_concurrency"),
            "isowner": ("commands.is_owner", "Owner-only command check.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.is_owner"),
            "haspermissions": ("commands.has_permissions", "User permission check.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.has_permissions"),
            "bothaspermissions": ("commands.bot_has_permissions", "Bot permission check.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.bot_has_permissions"),
            "guildonly": ("commands.guild_only", "Require guild invocation.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.guild_only"),
            "dmonly": ("commands.dm_only", "Require DM invocation.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.dm_only"),
            "helpcommand": ("commands.HelpCommand", "Base class for custom help commands.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.HelpCommand"),
            "paginator": ("commands.Paginator", "Text paginator helper.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Paginator"),
        },
    },
    "app_commands": {
        "title": "Application Commands",
        "url": "https://discordpy.readthedocs.io/en/stable/interactions/api.html",
        "topics": {
            "interaction": ("discord.Interaction", "Incoming interaction payload.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.Interaction"),
            "interactionresponse": ("discord.InteractionResponse", "Initial interaction response helper.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.InteractionResponse"),
            "webhookmessage": ("discord.WebhookMessage", "Message returned by interaction followups/webhooks.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.WebhookMessage"),
            "commandtree": ("app_commands.CommandTree", "Application command registry.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.app_commands.CommandTree"),
            "appcommand": ("app_commands.Command", "Application command object.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.app_commands.Command"),
            "appgroup": ("app_commands.Group", "Application command group.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.app_commands.Group"),
            "contextmenu": ("app_commands.ContextMenu", "User or message context menu command.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.app_commands.ContextMenu"),
            "transformer": ("app_commands.Transformer", "Slash command option transformer.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.app_commands.Transformer"),
            "choice": ("app_commands.Choice", "Slash command choice value.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.app_commands.Choice"),
            "range": ("app_commands.Range", "Numeric option bounds annotation.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.app_commands.Range"),
            "describe": ("app_commands.describe", "Set slash command parameter descriptions.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.app_commands.describe"),
            "choices": ("app_commands.choices", "Set slash command option choices.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.app_commands.choices"),
            "checks": ("app_commands.checks", "Application command checks and cooldowns.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#checks"),
        },
    },
    "ui": {
        "title": "discord.ui",
        "url": "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord-ui-kit",
        "topics": {
            "view": ("discord.ui.View", "Container for interactive components.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.ui.View"),
            "layoutview": ("discord.ui.LayoutView", "View supporting newer layout components.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.ui.LayoutView"),
            "button": ("discord.ui.Button", "Clickable button component.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.ui.Button"),
            "select": ("discord.ui.Select", "Dropdown/select menu component.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.ui.Select"),
            "modal": ("discord.ui.Modal", "Popup text input form.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.ui.Modal"),
            "textinput": ("discord.ui.TextInput", "Modal text input component.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.ui.TextInput"),
            "dynamicitem": ("discord.ui.DynamicItem", "Persistent dynamic component handler.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.ui.DynamicItem"),
        },
    },
    "tasks": {
        "title": "discord.ext.tasks",
        "url": "https://discordpy.readthedocs.io/en/stable/ext/tasks/",
        "topics": {
            "loop": ("tasks.Loop", "Managed background task loop.", "https://discordpy.readthedocs.io/en/stable/ext/tasks/index.html#discord.ext.tasks.Loop"),
            "looptask": ("tasks.loop", "Decorator that creates a Loop.", "https://discordpy.readthedocs.io/en/stable/ext/tasks/index.html#discord.ext.tasks.loop"),
        },
    },
    "voice": {
        "title": "Voice",
        "url": "https://discordpy.readthedocs.io/en/stable/api.html#voice",
        "topics": {
            "voiceclient": ("discord.VoiceClient", "Voice connection client.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.VoiceClient"),
            "audiosource": ("discord.AudioSource", "Base class for audio playback sources.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.AudioSource"),
            "ffmpegaudio": ("discord.FFmpegPCMAudio", "FFmpeg PCM audio source.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.FFmpegPCMAudio"),
            "pcmvolume": ("discord.PCMVolumeTransformer", "Audio volume transformer.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.PCMVolumeTransformer"),
        },
    },
    "exceptions": {
        "title": "Exceptions",
        "url": "https://discordpy.readthedocs.io/en/stable/api.html#exceptions",
        "topics": {
            "discordexception": ("discord.DiscordException", "Base discord.py exception.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.DiscordException"),
            "httpexception": ("discord.HTTPException", "HTTP API request failed.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.HTTPException"),
            "forbidden": ("discord.Forbidden", "HTTP 403 forbidden.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.Forbidden"),
            "notfound": ("discord.NotFound", "HTTP 404 not found.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.NotFound"),
            "loginfailure": ("discord.LoginFailure", "Bot token login failed.", "https://discordpy.readthedocs.io/en/stable/api.html#discord.LoginFailure"),
            "commanderror": ("commands.CommandError", "Base command extension error.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.CommandError"),
            "badargument": ("commands.BadArgument", "Command argument conversion failed.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.BadArgument"),
            "missingpermissions": ("commands.MissingPermissions", "User lacks required permissions.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.MissingPermissions"),
            "botmissingpermissions": ("commands.BotMissingPermissions", "Bot lacks required permissions.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.BotMissingPermissions"),
            "commandoncooldown": ("commands.CommandOnCooldown", "Command rate limit was hit.", "https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.CommandOnCooldown"),
            "appcommanderror": ("app_commands.AppCommandError", "Base app command error.", "https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.app_commands.AppCommandError"),
        },
    },
}


def iter_doc_topics():
    for category_key, category in DOC_CATEGORIES.items():
        for topic_key, (name, summary, url) in category["topics"].items():
            yield {
                "category_key": category_key,
                "category_title": category["title"],
                "topic_key": topic_key,
                "name": name,
                "summary": summary,
                "url": url,
            }


def find_doc_topic(query: str):
    needle = query.lower().strip()
    for topic in iter_doc_topics():
        values = (topic["topic_key"], topic["name"].lower(), topic["summary"].lower())
        if any(needle == value or needle in value for value in values):
            return topic
    return None
